"""Auto-generate API docs from DSL docstrings.

Two output formats:

  llm        — same shape as the historical metagen.benchmarks.code_api_description
               that was used in the assistant system prompts. Sections like
               "Skeleton Creation", "Lifting Procedures", etc., each
               containing one entry per symbol with @description / @params /
               @returns / @example_usage blocks.

  markdown   — human-readable Markdown rendering of the same data.

Each public DSL symbol carries a docstring with the same @-tagged structure
the LLM format expects. This module parses those docstrings, walks a
curated list of (section, symbol) entries, and renders the output. The
"Prebuilt Convex Polytopes" section is generated by introspecting the
cuboid/tet/triPrism instances directly.

Usage:

    python -m metagen_dsl.docs --format llm
    python -m metagen_dsl.docs --format markdown
    python -m metagen_dsl.docs --format llm --output api.txt

Or programmatically:

    from metagen_dsl._docgen import render_llm, render_markdown
    text = render_llm()
"""

from __future__ import annotations

import argparse
import inspect
import re
import sys
import textwrap
from dataclasses import dataclass, field
from typing import Iterable, Optional


# ---------------------------------------------------------------------------
# Curated public API: which symbol shows up in which section, in what order.
# Adding a new operator means appending a name here and giving it a
# @-tagged docstring; nothing else needs to change.
# ---------------------------------------------------------------------------

API_SECTIONS: list[tuple[str, list[str]]] = [
    ('Skeleton Creation', [
        'vertex', 'Polyline', 'Curve', 'skeleton',
    ]),
    ('Lifting Procedures', [
        'UniformBeams', 'SpatiallyVaryingBeams',
        'UniformDirectShell',
        'UniformTPMSShellViaConjugation', 'UniformTPMSShellViaMixedMinimal',
        'Spheres',
    ]),
    ('Tile Creation', [
        'Tile',
    ]),
    ('Patterning Procedures', [
        'TetFullMirror', 'TriPrismFullMirror', 'CuboidFullMirror',
        'Identity', 'Custom',
        'Mirror', 'Rotate180', 'Translate',
    ]),
    ('Structure Procedures', [
        'Structure', 'Union', 'Subtract', 'Intersect',
    ]),
]


# Convex polytope instances that appear in the "Prebuilt Convex Polytopes"
# section. Order matches the historical layout of code_api_description.
CP_INSTANCES = ['tet', 'triPrism', 'cuboid']

# Per-CP, the embed-method names to document (in order).
CP_EMBED_METHODS: dict[str, list[str]] = {
    'tet':      ['embed'],
    'triPrism': ['embed'],
    'cuboid':   ['embed', 'embed_via_minmax'],
}


# ---------------------------------------------------------------------------
# Boilerplate that prefaces the LLM format.
# ---------------------------------------------------------------------------

PREAMBLE = textwrap.dedent("""\
    Programs in Metagen are built in two stages: one that creates local
    geometric structure, and a second that patterns this structure throughout
    space. Each of these is further broken down into subparts.


    ==================================
        API description (Boilerplate)
    ==================================
    Each program is given as a python file (.py).
    This program must import the metagen_dsl package and define a function
    called "make_structure()" that returns the final Structure object defined
    by the program. If parameters are present in make_structure(), they MUST
    have a default value. Specifically:


    from metagen_dsl import *

    def make_structure() -> Structure:
        <content>
""")


# ---------------------------------------------------------------------------
# Docstring parser
# ---------------------------------------------------------------------------

# Lines like "@params:" mark the start of a structured section. The
# description is everything before the first @-tag.
_TAG_RE = re.compile(r'^\s*@(?P<tag>\w+)\s*:\s*$')


@dataclass
class ParsedDoc:
    description: str = ''
    requirements: str = ''
    params: list[tuple[str, str]] = field(default_factory=list)
    returns: list[tuple[str, str]] = field(default_factory=list)
    example_usage: str = ''


def _parse_param_lines(body: str) -> list[tuple[str, str]]:
    """Inside @params: / @returns: bodies, parse 'name - description' rows.

    Lines without a leading 'name -' are continuation lines for the previous
    entry.
    """
    out: list[tuple[str, str]] = []
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        # New entry: "name - description"
        m = re.match(r'^([A-Za-z_][\w-]*)\s*-\s*(.*)$', stripped)
        if m:
            out.append((m.group(1), m.group(2).rstrip()))
        elif out:
            # Continuation of previous entry's description.
            name, desc = out[-1]
            joined = (desc + ' ' + stripped).strip()
            out[-1] = (name, joined)
    return out


def parse_docstring(doc: str) -> ParsedDoc:
    """Pull description + @-sections out of a docstring."""
    if not doc:
        return ParsedDoc()
    text = textwrap.dedent(doc).strip()

    # First non-tag block is the description.
    sections: dict[str, list[str]] = {}
    current = 'description'
    sections[current] = []
    for line in text.splitlines():
        m = _TAG_RE.match(line)
        if m:
            current = m.group('tag').lower()
            sections.setdefault(current, [])
            continue
        sections[current].append(line)

    parsed = ParsedDoc()
    parsed.description = textwrap.dedent('\n'.join(sections.pop('description', []))).strip()
    parsed.requirements = textwrap.dedent('\n'.join(sections.pop('requirements', []))).strip()
    parsed.example_usage = textwrap.dedent('\n'.join(sections.pop('example_usage', ''))).strip()

    if 'params' in sections:
        parsed.params = _parse_param_lines('\n'.join(sections['params']))
    if 'returns' in sections:
        parsed.returns = _parse_param_lines('\n'.join(sections['returns']))
    return parsed


def _signature_line(name: str, obj, doc: ParsedDoc = None) -> str:
    """Render '<name>(<arg list>)' for the LLM/markdown output.

    The argument list comes from the docstring's @params when present — the
    docstring is the source of truth for the documented public surface
    (internal-use kwargs are kept out of the signature simply by not being
    documented). Falls back to inspect.signature if no @params block exists.
    """
    if doc is not None and doc.params:
        return f'{name}({", ".join(p for p, _ in doc.params)})'

    try:
        if inspect.isclass(obj):
            sig = inspect.signature(obj.__init__)
        else:
            sig = inspect.signature(obj)
    except (TypeError, ValueError):
        return f'{name}(...)'

    params = []
    for p in sig.parameters.values():
        if p.name == 'self':
            continue
        if p.kind in (inspect.Parameter.VAR_POSITIONAL, inspect.Parameter.VAR_KEYWORD):
            continue
        if p.name.startswith('_'):
            continue
        params.append(p.name)
    return f'{name}({", ".join(params)})'


# ---------------------------------------------------------------------------
# Symbol resolution
# ---------------------------------------------------------------------------

def _import_dsl():
    """Lazy import to avoid circular dependency at module-import time."""
    import metagen_dsl
    return metagen_dsl


def _get_symbol(name: str):
    return getattr(_import_dsl(), name, None)


def _iter_api_entries() -> Iterable[tuple[str, str, object, ParsedDoc]]:
    """Yield (section, name, obj, parsed_doc) for every API entry."""
    for section, names in API_SECTIONS:
        for name in names:
            obj = _get_symbol(name)
            if obj is None:
                continue
            doc = parse_docstring(inspect.getdoc(obj) or '')
            yield section, name, obj, doc


# ---------------------------------------------------------------------------
# CP introspection (entities + embed methods)
# ---------------------------------------------------------------------------

def _entity_names(collection) -> list[str]:
    """Names of entities in cuboid.corners / .edges / .faces."""
    return [getattr(e, 'name', None) for e in vars(collection).values()
            if hasattr(e, 'name') and not getattr(e, 'name', '').startswith('_')]


def _cp_entity_block(cp_name: str, cp_obj) -> str:
    """Render the entity-listing block for a CP (matches the historical
    code_api_description format: '<cp>.corners.{ ... }')."""
    parts: list[str] = []
    for kind in ('corners', 'edges', 'faces'):
        col = getattr(cp_obj, kind, None)
        if col is None:
            continue
        names = _entity_names(col)
        names = [n for n in names if n]
        if not names:
            continue
        joined = ',\n                '.join(names)
        parts.append(f'{cp_name}.{kind}.{{   {joined}\n            }}')
    return '\n'.join(parts)


def _cp_embed_entries(cp_name: str, cp_obj):
    """Yield (method_name, full_call, parsed_doc) for each embed method."""
    for meth_name in CP_EMBED_METHODS.get(cp_name, []):
        method = getattr(cp_obj, meth_name, None)
        if method is None:
            continue
        sig = inspect.signature(method)
        params = []
        for p in sig.parameters.values():
            if p.name in ('self', 'kwargs') or p.name.startswith('_'):
                continue
            if p.kind == inspect.Parameter.VAR_KEYWORD:
                continue
            params.append(p.name)
        full_call = f'{cp_name}.{meth_name}({", ".join(params)})'
        parsed = parse_docstring(inspect.getdoc(method) or '')
        yield meth_name, full_call, parsed


# ---------------------------------------------------------------------------
# LLM-format renderer (matches the historical code_api_description shape)
# ---------------------------------------------------------------------------

_LLM_SECTION_BAR = '======= {title} ========'


def _render_llm_entry(name: str, obj, doc: ParsedDoc, signature_override: str = None) -> str:
    """Render a single API entry in the LLM format."""
    sig = signature_override or _signature_line(name, obj, doc)
    out = [sig]
    out.append('    @description:')
    out.append(textwrap.indent(doc.description, '        '))
    if doc.requirements:
        out.append('    @requirements:')
        out.append(textwrap.indent(doc.requirements, '        '))
    if doc.params:
        out.append('    @params:')
        for pname, pdesc in doc.params:
            out.append(f'        {pname:<16}- {pdesc}')
    else:
        out.append('    @params:')
        out.append('        N/A')
    if doc.returns:
        out.append('    @returns:')
        for rname, rdesc in doc.returns:
            out.append(f'        {rname:<16}- {rdesc}')
    if doc.example_usage:
        out.append('    @example_usage:')
        out.append(textwrap.indent(doc.example_usage, '        '))
    return '\n'.join(out)


def render_llm() -> str:
    """Render the full LLM-formatted API description."""
    out = [PREAMBLE.rstrip(), '',
           '==================================',
           '    DSL description',
           '==================================', '']

    # API sections.
    for section, names in API_SECTIONS:
        out.append('')
        out.append(_LLM_SECTION_BAR.format(title=section))
        for name in names:
            obj = _get_symbol(name)
            if obj is None:
                continue
            doc = parse_docstring(inspect.getdoc(obj) or '')
            out.append(_render_llm_entry(name, obj, doc))
            out.append('')

    # Prebuilt Convex Polytopes section.
    out.append('')
    out.append('==================================')
    out.append('    Prebuilt Convex Polytopes')
    out.append('==================================')
    out.append(
        'There are 3 prebuilt convex polytopes (CP) available for use: '
        'cuboid, triPrism, and tet. Each CP comprises a set of Entities, '
        'namely faces, edges and corners. For convenience, each individual '
        'entity can be referenced using the pattern '
        '<CP>.<entity_type>.<ENTITY_NAME>. For example, you can select a '
        'particular edge of the cuboid with the notation '
        'cuboid.edges.BOTTOM_RIGHT. Each CP also has an embed() method '
        'which returns all necessary information to embed the CP within R^3.'
    )
    out.append('')
    out.append('The full list of entities and embed() method signatures '
               'for our predefined CPs are as follows:')
    out.append('')

    dsl = _import_dsl()
    for cp_name in CP_INSTANCES:
        cp_obj = getattr(dsl, cp_name, None)
        if cp_obj is None:
            continue
        out.append(_cp_entity_block(cp_name, cp_obj))
        for meth_name, full_call, parsed in _cp_embed_entries(cp_name, cp_obj):
            # Render the embed method using the same shape as other entries.
            out.append(_render_llm_entry(meth_name, None, parsed,
                                         signature_override=full_call))
            out.append('')

    return '\n'.join(out).rstrip() + '\n'


# ---------------------------------------------------------------------------
# Markdown renderer
# ---------------------------------------------------------------------------

def _render_md_entry(name: str, obj, doc: ParsedDoc, signature_override: str = None) -> str:
    sig = signature_override or _signature_line(name, obj, doc)
    lines = [f'### `{sig}`', '']
    if doc.description:
        lines.append(doc.description)
        lines.append('')
    if doc.requirements:
        lines.append('**Requirements:**')
        lines.append('')
        lines.append(doc.requirements)
        lines.append('')
    if doc.params:
        lines.append('**Parameters:**')
        lines.append('')
        for pname, pdesc in doc.params:
            lines.append(f'- `{pname}` — {pdesc}')
        lines.append('')
    if doc.returns:
        lines.append('**Returns:**')
        lines.append('')
        for rname, rdesc in doc.returns:
            lines.append(f'- `{rname}` — {rdesc}')
        lines.append('')
    if doc.example_usage:
        lines.append('**Example:**')
        lines.append('')
        lines.append('```python')
        lines.append(doc.example_usage)
        lines.append('```')
        lines.append('')
    return '\n'.join(lines)


def render_markdown() -> str:
    out = ['# metagen-dsl API reference', '']
    out.append(PREAMBLE.strip().split('\n\n', 1)[0])
    out.append('')
    out.append('Each program is a Python file that imports `metagen_dsl` and '
               'defines `make_structure()` returning a `Structure`:')
    out.append('')
    out.append('```python')
    out.append('from metagen_dsl import *')
    out.append('')
    out.append('def make_structure() -> Structure:')
    out.append('    ...')
    out.append('```')
    out.append('')

    for section, names in API_SECTIONS:
        out.append(f'## {section}')
        out.append('')
        for name in names:
            obj = _get_symbol(name)
            if obj is None:
                continue
            doc = parse_docstring(inspect.getdoc(obj) or '')
            out.append(_render_md_entry(name, obj, doc))

    # CPs.
    out.append('## Prebuilt Convex Polytopes')
    out.append('')
    out.append(
        'Three predefined convex polytopes are available: `cuboid`, '
        '`triPrism`, and `tet`. Each exposes its `corners`, `edges`, and '
        '`faces` as named entities, plus one or more `embed*` methods that '
        'place the CP in R^3.'
    )
    out.append('')

    dsl = _import_dsl()
    for cp_name in CP_INSTANCES:
        cp_obj = getattr(dsl, cp_name, None)
        if cp_obj is None:
            continue
        out.append(f'### `{cp_name}`')
        out.append('')
        for kind in ('corners', 'edges', 'faces'):
            col = getattr(cp_obj, kind, None)
            if col is None:
                continue
            names = [n for n in _entity_names(col) if n]
            if not names:
                continue
            out.append(f'`{cp_name}.{kind}`: {", ".join(f"`{n}`" for n in names)}')
            out.append('')
        for meth_name, full_call, parsed in _cp_embed_entries(cp_name, cp_obj):
            out.append(_render_md_entry(meth_name, None, parsed,
                                        signature_override=full_call))

    return '\n'.join(out).rstrip() + '\n'


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: Optional[list[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--format', choices=['llm', 'markdown'], required=True,
                    help='Output format.')
    ap.add_argument('--output', '-o',
                    help='Write to this path. Default: stdout.')
    args = ap.parse_args(argv)

    if args.format == 'llm':
        text = render_llm()
    else:
        text = render_markdown()

    if args.output:
        with open(args.output, 'w') as f:
            f.write(text)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
